version: '2'
services:

  terribot:
    build: .
    depends_on:
      - tg
    links:
      - tg
    volumes_from:
      - tg

  tg:
    image: justingood/tg
    ports:
      - "4458:4458"
    volumes:
      - $HOME/.telegram-cli:/home/telegram/.telegram-cli
      - /tmp
