version: '2'
services:

  terribot:
    image: justingood/terribot
    build: .
    cpu_shares: 2
    mem_limit: 32m
    restart: always
    depends_on:
      - tg
    links:
      - tg
    volumes_from:
      - tg

  tg:
    image: justingood/tg
    cpu_shares: 2
    mem_limit: 8m
    restart: always
    volumes:
      - $HOME/.telegram-cli:/home/telegram/.telegram-cli
      - /tmp
